### ISSUE TITLE
Docker needs Gemfile.lock

### ISSUE THREAD

**Issue by sebbASF** [apache/privacy-website#29]
Docker currently fails to build because it needs Gemfile.lock
However this is not present in the source, and is excluded in .gitignore.

The Dockerfile and/or .gitignore need to be updated

**Comment by grobmeier** [comment]
I think it is better to remove the copy Gemfile directive - otherwise one would have to create it outside the container. Not sure if this is the best approach. Thanks!

Fixed with ad78213429e3114fa7445aa6b231de1382d0a799
