### ISSUE TITLE
Lines are much too long

### ISSUE THREAD

**Issue by sebbASF** [apache/privacy-website#6]
https://github.com/apache/privacy-website/blob/c47b3ea271bb301846e701a8b35987746506bee9/policies/privacy-policy-public.md?plain=1#L25

The lines in this file are really long. This makes it very hard to review the source via GitHub, as the window has to be scrolled.
Likewise difference emails are much harder to read.

**Comment by sebbASF** [comment]
See #11 and #12

**Comment by grobmeier** [comment]
Merged both, thanks Sebb!
