### ISSUE TITLE
Does not read well

### ISSUE THREAD

**Issue by sebbASF** [apache/privacy-website#9]
https://github.com/apache/privacy-website/blob/c47b3ea271bb301846e701a8b35987746506bee9/policies/privacy-policy-public.md?plain=1#L56-L58

The following list items do not read well:
 - ensuring a smooth connection of the website,
 - ensuring comfortable use of our website,
 - Evaluation of system security and stability as well

What is a "smooth connection"?
Comfortable?
"as well" as what?

**Comment by grobmeier** [comment]
@sebbASF I have tried to fix the points you mentioned. I am not a native speaker. If you have further suggestions, please feel free to reopen this issue or even send a PR. Super happy about your comments, thanks!
